[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.npm"]

[phases.install]
cmds = ["npm i"]

[phases.build]
cmds = ["npx prisma generate"]

[start]
cmd = "npx prisma db push --accept-data-loss && node src/index.js"
