// English word list for username availability checking
// Add more words as needed
export const enWords = new Set([
  // From screenshots & common desirable handles
  'saboted','pianolist','spiritualty','cosying','autolyzing',
  'silently','luminous','radiant','ethereal','celestial','aurora',
  'zenith','nexus','cipher','phantom','rogue','noble','valor',
  'virtue','wisdom','vision','legacy','empire','atlas','omega',
  'eclipse','mirage','reverie','solace','haven','refuge','serene',
  'tranquil','eloquent','devoted','majestic','glorious','resilient',
  'enduring','flourish','blossom','triumph','conquer','prevail',
  'succeed','persist','inspire','elevate','illuminate','captivate',
  'enchant','mesmerize','fascinate','explore','discover','achieve',
  // Verbs and verb forms (common username style)
  'blossom','glimmer','shimmer','flicker','wander','ponder',
  'linger','whisper','murmur','thunder','conquer','gather',
  'wither','scatter','shatter','clatter','flutter','stutter',
  'mutter','utter','clutter','sputter','bitter','glitter',
  'twitter','twitter','quitter','fitter','hitter','knitter',
  'splitter','gritter','critter','fritter','litter','sitter',
  'emitter','transmit','permit','summit','commit','submit',
  'omit','admit','limit','spirit','merit','ferret',
  // Adjectives / descriptors popular as handles
  'vivid','lavish','savage','sleek','swift','bold','brave',
  'smart','sharp','clean','clear','deep','dark','wild',
  'calm','cool','cold','warm','soft','hard','loud','quiet',
  'bright','light','dense','vast','thin','wide','long','short',
  'great','large','small','tiny','huge','giant','grand','solid',
  'hollow','shallow','narrow','broad','steep','flat','round',
  'curved','sharp','blunt','rough','smooth','coarse','fine',
  // Nouns — popular username categories
  'shadow','blade','storm','flame','frost','ember','ash',
  'dust','mist','fog','tide','wave','reef','shore','crest',
  'peak','ridge','cliff','vale','grove','field','meadow',
  'forest','jungle','desert','canyon','valley','river','lake',
  'ocean','island','coast','harbor','vessel','anchor','compass',
  'arrow','sword','shield','crown','throne','castle','tower',
  'bridge','portal','gateway','nexus','vertex','prism','lens',
  'mirror','sphere','orbit','comet','meteor','galaxy','nebula',
  'quasar','pulsar','nova','zenith','nadir','apex','core',
  // Common 4-6 letter handles that come available
  'craft','draft','shaft','swift','shift','drift','lift','gift',
  'built','guilt','quilt','spilt','wilt','melt','felt','dealt',
  'knelt','smelt','dwelt','belt','bolt','colt','jolt','molt',
  'moult','vault','fault','halt','malt','salt','waltz','waltz',
  'bands','lands','sands','hands','wands','bonds','ponds','funds',
  'bends','lends','sends','tends','fends','rends','wends','blends',
  'mends','trends','spends','extends','amends','offends','defends',
  // Longer desirable words
  'abstract','acoustic','adaptive','adhesive','adjacent','affinity',
  'affluent','agnostic','alchemy','alliance','almighty','altitude',
  'ambience','ambition','analytic','ancestry','ancient','android',
  'anomaly','antidote','archival','ardently','artifact','ascendant',
  'astonish','astrolab','attained','audacity','aurelius','authentic',
  'autonomy','balanced','becoming','benevolent','blissful','brilliance',
  'cascade','champion','cherished','chromatic','clarity','cluster',
  'cognition','coherent','commence','composed','conclave','constant',
  'contrast','creative','crimson','crucial','crystal','cyclone',
  'daybreak','dazzling','decisive','defiant','devoted','digital',
  'distinct','dominant','dramatic','dreaming','dynamic','earnest',
  'eclipse','elusive','emerald','empathy','endured','enigma',
  'essence','eternal','evolved','exalted','excited','explicit',
  'extreme','fabled','factual','faithful','famous','fearless',
  'fervent','fiction','flowing','focused','formula','fortune',
  'forward','fractal','freedom','frontier','frozen','fulfill',
  'genuine','gifted','gilded','glacier','gleaming','glowing',
  'golden','gracing','granted','gravity','guardian','guiding',
  'hallmark','harmony','healing','heroic','holistic','horizon',
  'humbled','hunter','hustle','hybrid','ignited','imagery',
  'immense','immortal','impact','impulse','infinite','instinct',
  'intense','invoked','journey','justice','kinetic','kingly',
]);
