// Lista de palavras portuguesas para verificação de username
// Adicione mais palavras conforme necessário (uma por linha)
export const ptWords = new Set([
  // Verbos conjugados (gerúndio, passado, presente)
  'orgulhando','socorriam','curtimos','brilhando','correndo','sorrindo',
  'cantando','dançando','voando','lutando','vencendo','crescendo',
  'vivendo','amando','sonhando','adorando','rindo','chorando',
  'querendo','podendo','sabendo','fazendo','tendo','sendo','vindo',
  'dando','olhando','falando','ouvindo','sentindo','pedindo','trazendo',
  'mostrando','usando','colocando','virando','ficando','voltando',
  'levando','trocando','mudando','jogando','trabalhando','estudando',
  'aprendendo','ensinando','ajudando','cuidando','tentando','esperando',
  'pensando','lembrando','perdendo','ganhando','caindo','subindo',
  'descendo','abrindo','fechando','partindo','chegando','saindo',
  'entrando','passando','seguindo','chamando','contando','deixando',
  'tomando','bebendo','comendo','dormindo','acordando','levantando',
  'sentando','andando','parando','começando','terminando','acabando',
  'criando','construindo','destruindo','salvando','matando','nascendo',
  'morendo','casando','amando','beijando','abraçando','abracos',
  'saudade','verdade','amizade','coragem','vitoria','liberdade',
  'felicidade','realidade','esperanca','tristeza','alegria','bondade',
  'maldade','riqueza','pobreza','beleza','feiura','grandeza','firmeza',
  // Substantivos comuns
  'iberismo','saudades','segredos','sonhos','amigos','familia',
  'natureza','universo','estrelas','oceanos','montanha','floresta',
  'cidade','paixao','carinho','respeito','honra','dignidade','orgulho',
  'coracao','espirito','almas','destino','caminho','jornada',
  'aventura','missao','visao','criacao','evolucao','revolucao',
  'salvacao','devocao','paixoes','emocoes','sensacoes','decisoes',
  'posicoes','versoes','situacao','solucao','acao','relacao',
  // Adjetivos
  'bonito','bonita','lindo','linda','forte','fraco','rapido','lento',
  'grande','pequeno','alto','baixo','novo','velho','jovem','maduro',
  'simples','complexo','perfeito','imperfeito','eterno','momentaneo',
  'feliz','triste','bravo','calmo','ansioso','tranquilo','agitado',
  'corajoso','medroso','honesto','curioso','criativo','inteligente',
  'sábio','tolo','gentil','cruel','generoso','avarento','paciente',
  // Palavras compostas / derivadas
  'endividamo','orgulhamos','saudoso','saudosa','verdadeiro','verdadeira',
  'amigavel','corajosa','vitorioso','vitoriosa','livremente','felizmente',
  'realmente','finalmente','certamente','provavelmente','naturalmente',
  'completamente','simplesmente','exatamente','totalmente','absolutamente',
  'especialmente','principalmente','geralmente','normalmente','raramente',
  'frequentemente','constantemente','eternamente','temporariamente',
  // Mais palavras brasileiras populares
  'bagunça','maravilha','sorriso','silencio','mistério','milagre',
  'fenomeno','símbolo','exemplo','modelo','padrao','formato',
  'sistema','metodo','processo','resultado','produto','servico',
  'recurso','energia','forca','poder','controle','dominio',
  'sucesso','fracasso','vitoria','derrota','progresso','regresso',
  'futuro','passado','presente','momento','instante','segundo',
  'minuto','tempo','espaco','lugar','mundo','pais','cidade',
  'terra','agua','fogo','ar','luz','sombra','dia','noite',
  'manha','tarde','vida','morte','amor','odio','paz','guerra',
]);
