// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/profile-redesign/KosameProfile.tsx": () => import("../components/mockups/profile-redesign/KosameProfile.tsx")
};
